package:
  name: blickfeld_scanner
  version: @BF_BSL_PYTHON_VERSION@

source:
  path: ./

build:
  noarch: python

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - protobuf>=3.6.1
    - zeroconf
